### ISSUE TITLE
在配置git时出现如下问题，(windows)

### ISSUE THREAD

**Issue by xuejm9999** [tsq/vscode-course#11]
'eval' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tsq** [comment]
像视频中的那样，需要使用安装git时，附带被安装的bash。windows自带的command prompt或者powershell中是没用'eval'这个命令的。

**Comment by xuejm9999** [comment]
> 像视频中的那样，需要使用安装git时，附带被安装的bash。windows自带的command prompt或者powershell中是没用'eval'这个命令的。

收到，多谢及时回复。我重新安装下git
