### ISSUE TITLE
为什么我的terminal没有shell的选择栏

### ISSUE THREAD

**Issue by xuejm9999** [tsq/vscode-course#12]
你好阿汤，
为什么我的terminal没有shell的选择栏？见图片
![Capture6](https://user-images.githubusercontent.com/74894862/185743981-315ea207-657b-4dd0-8673-770b730f29f5.JPG)

![Capture5](https://user-images.githubusercontent.com/74894862/185743986-9d3ee2bb-220d-483d-8122-4d34dd5e72bb.JPG)

**Comment by tsq** [comment]
可能和vscode的版本有关吧，加号旁的下箭头是吗？[image: Screen Shot 2022-08-22 at 21.56.04.png]
