### ISSUE TITLE
这么好的教程，为什么不更新了呢？

### ISSUE THREAD

**Issue by seryte** [tsq/vscode-course#13]
视频一集不落全看完了，楼主讲解条理清楚，由浅入深，收益颇多，可惜不更新了， 还会更新吗，非常期待

**Comment by tsq** [comment]
谢谢你的留言！后面会更新的，但是具体时间还不能确定。

**Comment by seryte** [comment]
那就翘首以盼了👍👍👍

> 谢谢你的留言！后面会更新的，但是具体时间还不能确定。
