### ISSUE TITLE
非常期待博主能更新

### ISSUE THREAD

**Issue by letsencrypt6** [tsq/vscode-course#14]
花了3天的时间，把Youtube上的视频都看了一遍，收获非常多，非常适合入门，介绍的极其详细。期待能在2023年更新完，谢谢博主

**Comment by tsq** [comment]
谢谢支持，后续会更新的。

**Comment by letsencrypt6** [comment]
希望博主能在2023年完成2020的vscode的课，不然vscode的版本差距太大，后续功能和按钮位置或者图形界面变化稍微大点，就不容易和前面的视频联系在一起了。多谢博主

**Comment by FanruiC** [comment]
期待一个更新

**Comment by LukerSpringtree** [comment]
> 谢谢支持，后续会更新的。

@tsq 非常棒的课程, 期待继续更新.

**Comment by xutaoustc** [comment]
这么好的课程，为什么不更新了呢。。
