### ISSUE TITLE
Fix shortcut on windows

### ISSUE THREAD

**Issue by tsq** [tsq/vscode-course#3]
# 39 Status bar

Shift+Alt+F

**Comment by SeikoLi** [comment]
请教一下大佬在vscode中使用Code runner运行代码时输出窗口乱码是什么原因？

**Comment by tsq** [comment]
可能是因为输出窗口不支持utf8编码导致的，可以参考这篇文章的解决办法：
https://blog.csdn.net/qq_43827595/article/details/100151456
