### ISSUE TITLE
An Question about launch.json 

### ISSUE THREAD

**Issue by lez8sgh** [tsq/vscode-course#6]
你好！首先感謝你的視頻。你的視頻條理清楚，簡單明瞭。
在視頻24裏面，我有1個問題: 當創建launch.json文件后，最後一行是：“program": "${workspaceFolder}/app.js" 這樣在Sidebar的Debug功能裏，我選中“Launch Program", 每次點擊Run按鈕，都啓動app.js文件。如果我有兩個文件，我想debug另一個JS文件。該怎麽做？

**Comment by tsq** [comment]
如果还有另外一个文件，比如叫“app2.js”, 为了调试它，只需要将最后一行改为：

```json
"program": "${workspaceFolder}/app2.js"
```

**Comment by lez8sgh** [comment]
@tsq 看來是每個文件，在launch.json裏面，都得有一個自己的調試文件塊, 如:
{  xxx;
"program": "${workspaceFolder}/app.js"  }
{xxx;
"program": "${workspaceFolder}/app2.js" }

這樣對嗎？

**Comment by tsq** [comment]
对的，这样Sidebar的Debug功能里，下拉框里就会有两个选项，调试时，选择想要的调试项即可。

**Comment by lez8sgh** [comment]
clear. tks!
