### ISSUE TITLE
Serve

### ISSUE THREAD

**Issue by lez8sgh** [tsq/vscode-course#7]
Tip2: 课程中用到的serve命令，可以通过下面的命令来安装：
npm i -g serve

能不能詳細的講講這個。 我的出了一推問題，不知道如何分析。
pm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/serve failed, reason: getaddrinfo ENOTFOUND 
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
。。。

**Comment by tsq** [comment]
你好，这个问题是说，本地网络出现了问题，无法和npm的服务器取得连接。

解决办法：你可以换个wifi试下，看看还有没有同样的问题，如果还是同样的错误，可能就要查一下正如上面报错信息最后三行写得，是不是本地网络用了proxy，用了的话，需要先做好相应的配置才行。

**Comment by lez8sgh** [comment]
是的，用的公司电脑，上网后vpn连接公司网络上网，在internet browser的option的选项里有公司proxy的设置。
这种情况怎样做设置呢？

**Comment by tsq** [comment]
不好意思，我没有使用vpn连接网络的使用经验，所以也不知道该怎么做。

或许可以参考下这篇文章：https://stackoverflow.com/questions/7559648/is-there-a-way-to-make-npm-install-the-command-to-work-behind-proxy
